services:
  sonarqube:
    image: sonarqube:lts-community
    ports:
      - "9001:9000"
    networks:
      - sonar_network
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres-sonar-db:5432/sonarqube
      - SONAR_JDBC_USERNAME=test_sonar_user
      - SONAR_JDBC_PASSWORD=test_sonar_passw0rd
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
    depends_on:
      - postgres-sonar-db

  postgres-sonar-db:
    image: postgres:latest
    networks:
      - sonar_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test_sonar_user
      - POSTGRES_PASSWORD=test_sonar_passw0rd
      - POSTGRES_DB=sonarqube
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonar_network:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  postgresql:
  postgresql_data: